version: "3.9"

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5433:5432
    volumes:
      - jimvolume:/var/lib/postgresql/data
    env_file:
      - ./env/dockerComposeVariables.env


volumes:
  jimvolume: